name: kidney_care_mart
version: 1.0.0
config-version: 2

profile: kidney_care_mart

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
clean-targets: ["target", "dbt_packages", "logs"]

models:
  kidney_care_mart:
    staging:
      +materialized: table
