{{ config(contract={"enforced": true}) }}

select
    county_fips,
    svi_vintage,
    acs_period_start,
    acs_period_end,
    rpl_themes,
    rpl_themes_status,
    rpl_theme1,
    rpl_theme1_status,
    rpl_theme2,
    rpl_theme2_status,
    rpl_theme3,
    rpl_theme3_status,
    rpl_theme4,
    rpl_theme4_status,
    ep_pov150,
    ep_pov150_status,
    ep_uninsur,
    ep_uninsur_status,
    ep_age65,
    ep_age65_status,
    ep_disabl,
    ep_disabl_status,
    ep_limeng,
    ep_limeng_status,
    ep_noveh,
    ep_noveh_status,
    source_id,
    source_manifest_run_id,
    source_snapshot_sha256,
    source_retrieved_at_utc,
    source_modified_at
from {{ ref('stg_cdc_svi_county_2022') }}
